"""init

Revision ID: 511d25172d82
Revises: 
Create Date: 2026-07-03 12:12:40.113704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511d25172d82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('feed_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('human_priority', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags_raw', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ai_priority', sa.Integer(), nullable=False),
    sa.Column('ai_tech_tags', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_data_ai_priority'), 'job_data', ['ai_priority'], unique=False)
    op.create_index(op.f('ix_job_data_external_id'), 'job_data', ['external_id'], unique=True)
    op.create_table('active_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['job_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_jobs')
    op.drop_index(op.f('ix_job_data_external_id'), table_name='job_data')
    op.drop_index(op.f('ix_job_data_ai_priority'), table_name='job_data')
    op.drop_table('job_data')
    # ### end Alembic commands ###
