"""add_is_closed

Revision ID: a957b74f5029
Revises: ce0a25fe0609
Create Date: 2026-05-10 15:27:50.395183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a957b74f5029'
down_revision: Union[str, Sequence[str], None] = 'ce0a25fe0609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_dataset', sa.Column('is_closed', sa.Boolean(), nullable=False, server_default=sa.text("False")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_dataset', 'is_closed')
    # ### end Alembic commands ###
