"""init

Revision ID: ac5da20a7114
Revises: 
Create Date: 2026-05-03 20:14:55.167714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5da20a7114'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('human_priority', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags_raw', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ai_priority', sa.Integer(), nullable=False),
    sa.Column('ai_tech_tags', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('basic_priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_dataset_ai_priority'), 'training_dataset', ['ai_priority'], unique=False)
    op.create_index(op.f('ix_training_dataset_external_id'), 'training_dataset', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_dataset_external_id'), table_name='training_dataset')
    op.drop_index(op.f('ix_training_dataset_ai_priority'), table_name='training_dataset')
    op.drop_table('training_dataset')
    # ### end Alembic commands ###
