"""delete_basic_priority

Revision ID: ce0a25fe0609
Revises: ac5da20a7114
Create Date: 2026-05-04 14:25:47.208136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0a25fe0609'
down_revision: Union[str, Sequence[str], None] = 'ac5da20a7114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_dataset', 'basic_priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_dataset', sa.Column('basic_priority', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
