"""init

Revision ID: e736e157c9ba
Revises: 
Create Date: 2026-07-12 14:51:58.710913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e736e157c9ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('feed_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags_raw', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('0', '1', '2', '3')", name='check_priority'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_data_external_id'), 'job_data', ['external_id'], unique=True)
    op.create_table('ai_analysis',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_job_data_external_id'), table_name='job_data')
    op.drop_table('job_data')
    # ### end Alembic commands ###
